print ("Desafio 2")
dia = input("Qual o dia que você nasceu?")
mês = input ("Qual o mês que você nasceu?")
ano = input("Qual o ano que você nasceu?")
print ("Você nasceu em", dia, "de", mês, "de", ano, "correto?")
